config/routes.rb
Rails.application.routes.draw do
  
  resources :boards do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
    resources :etapas


  root "boards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :tasks
  validates_associated :tasks
  validates :title, presence: { message: "can't be blank"} 
  validates :title, uniqueness: { case_sensitive: false, message: "are uniquenes"} 
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :board
  has_many :etapas
  validates :title, presence: { message: "can't be blank"} 
  def completed?
   !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    # respond_to do |format|
      if @board.save
        redirect_to root_url, notice: "Board was successfully created."
      else
        render :new
      end
    # end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    # respond_to do |format|
      if @board.update(board_params)
        redirect_to root_url, notice: "Board was successfully updated."
      else
        render :edit
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
   if @board.tasks.empty?
      @board.destroy
      redirect_to root_url, notice: "Board was successfully destroyed."
   else
      redirect_to root_url, alert: "Board cannot be destroyed, because it still has tasks."
  end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_board
  before_action :set_task, except: [:create]

  def create 
    @task = @board.tasks.create(task_params)
    redirect_to @board, notice: "Task was successfully created.."
  end
  
  def show
  end

  def destroy 
    if @task.destroy
      flash[:notice]= "Board item was deleted."
    else
      flash[:alert] = "Board could not be deleted."
    end
    redirect_to @board
  end

  def complete
     @task.update_attribute(:completed_at, Time.now)
     redirect_to @board, notice: "Task completed"
  end

  
  private

  def set_board
    @board = Board.find(params[:board_id]) 
  end

  def set_task 
    @task = @board.tasks.find(params[:id])
  end
  def task_params
    params[:task].permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/etapa_helper.rb
module EtapaHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
<% if board.errors.any? %>
<h2>Errors:</h2>
<ul>
  <% @board.errors.full_messages.each do |message|%>
  <li><%=message%></li>
  <%end%>
</ul>
<% end %>
<div class="field">
  <div class="text-white">
    <%= form.label :title %>
  </div>
  <%= form.text_field :title %>
</div>

<div class="actions">
  <%= form.submit 'Submit', :class => 'btn btn-light btn-sm' %>
</div>
<% end %>

app/views/boards/edit.html.erb
<div class="container">

  <h1>Editing Board</h1>

  <div class="row">
    <div class="card m-2 bg-primary" style="width: 20rem;">
      <div class="card-body">
        <%= render 'form', board: @board %>
        <div class="btn-group  ">
          <%= link_to 'Show', @board, class: "btn btn-sm btn-primary text-light" %>
          <%= link_to 'Back', boards_path, class:"btn btn-sm btn-primary text-light"  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<% if notice %>
<div id="notice_wrapper">
</div>
<%end%>
<div class="container">

  <p>
    <%= link_to 'New Board', new_board_path, class:" btn btn-primary btn-lg text-light" %>
  </p>
  <div class="row">
    <% @boards.each do |board| %>
    <div class="card m-2 bg-primary" style="width: 20rem;">
      <div class="card-body">
        <div class="card-title font-weight-bold text-white">
          <%= board.title %>
        </div>
        <div class="d-flex justify-content-between align-items-center">
          <div class="card bg-light">
            <div class="btn-group  ">
              <%= link_to 'Show', board, class: "btn btn-light btn-sm" %>
              <%= link_to 'Edit', edit_board_path(board), class:"btn btn-light btn-sm"  %>
              <%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-light btn-sm " %>
            </div>
          </div>
        </div>

      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container">
  <h1>New Board</h1>
  <div class="row">
    <div class="card m-2 bg-primary" style="width: 20rem;">
      <div class="card-body">
        <%= render 'form', board: @board %>
        <div class="btn-group  ">
          <%= link_to 'Back', boards_path, class: "btn btn-light btn-sm " %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="container">
  <h1>
    <%= @board.title %>
  </h1>
  <div class="row">
    <div class="col">
      <div class="card">
        <%= render @board.tasks%>
      </div>
    </div>

    <div class="col-4">
      <%= render "tasks/form" %>
      <div class="btn-group">
        <%= link_to 'Edit', edit_board_path(@board), class: "btn btn-sm btn-primary text-light" %>
        <%= link_to 'Back', boards_path , class: "btn btn-sm btn-primary text-light" %>
      </div>
    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TodoList</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
  <div class="site-header bg-primary text-light font-weight-bolder">
    <div>TODO LIST</div>
  </div>


  <% if flash[:notice] %>
  <div class="container">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>

  <%elsif flash[:alert]%>
  <div class="container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  <%end%>

  <%= yield %>
</body>

</html>

app/views/tasks/_form.html.erb
<%= form_for([@board, @board.tasks.build]) do |f| %>
<div class="input-group mb-3">
  <%= f.text_field :title, placeholder: "New Task" , class: "form-control" %>
  <%= f.submit 'Create', :class => 'btn btn-primary btn-outline-white'%>
</div>
<%end%>

app/views/tasks/_task.html.erb
<div class="container ">
  <% if task.completed?%>
  <div class="row tg-mg-5">
    <div class="col  rounded">
      <div class="complete">
        <%= link_to  complete_board_task_path(@board, task.id), method: :patch do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
        <%end%>
      </div>
    </div>
    <div class="col-6 rounded">
      <div class="card-text font-weight-bold text-black " style="opacity: 0.4;">
        <strike>
          <%= task.title%>
        </strike>
      </div>
    </div>
    <div class="col border rounded">
      <div class="trash text-center ">
        <%= link_to board_task_path(@board, task.id), method: :delete, data: { confirm: "Are you sure?"} do%>
        <i class="fa fa-trash"></i>
        <%end%>
      </div>
    </div>
  </div>
  <%else%>
  <div class="row tg-mg-5 shadow-sm">
    <div class="col rounded">
      <div class="complete">
        <%= link_to complete_board_task_path(@board, task.id), method: :patch do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
        <%end%>
      </div>
    </div>
    <div class="col-6 rounded">
      <div class="card-text font-weight-bold text-black">
        <%= task.title%>
      </div>
    </div>
    <div class="col rounded">
      <div class="trash text-center">
        <%= link_to board_task_path(@board, task.id), method: :delete, data: { confirm: "Are you sure?"} do%>
        <i class="fa fa-trash"></i>
        <%end%>
      </div>
    </div>
  </div>
  <%end%>
</div>